[extend]
useDefault = true

[[rules]]
id = "helius-api-key"
description = "Helius API Key"
regex = '''[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
keywords = ["helius", "api-key", "16b9324a"]

[[rules]]
id = "solana-private-key"
description = "Solana Private Key"
regex = '''[1-9A-HJ-NP-Za-km-z]{87,88}'''
keywords = ["private", "secret", "key"]

[[rules]]
id = "treasury-address"
description = "Treasury Address"
regex = '''EdFC98d1BBhJkeh7KDq26TwEGLeznhoyYsY6Y8LFY4y6'''
keywords = ["treasury", "owner"]

[allowlist]
paths = [
  ".gitleaks.toml",
  "README.md",
  "FUTURISTIC_KAMI_CONTRACT_REGISTRY.md",
  "EXTRACTED_ADDRESSES.json"
]